### ISSUE TITLE
Module 6, Step 27: Can't delete volume

### ISSUE THREAD

**Issue by cr20ro20** [FireballDWF/securityhub-remediations#34]
TeamRole:~/environment/securityhub-remediations (master) $ aws ec2 delete-volume --volume-id $WorkshopVolumeId

An error occurred (UnauthorizedOperation) when calling the DeleteVolume operation: You are not authorized to perform this operation. Encoded authorization failure message: ...

TeamRole:~/environment/securityhub-remediations (master) $ echo $WorkshopVolumeId
vol-0956d0d5bb49e5662

**Comment by FireballDWF** [comment]
I updated the iam actions allowed so in the future this with work
