### ISSUE TITLE
Module 6, Steps 27: volume cannot be deleted in the AWS Event

### ISSUE THREAD

**Issue by Luk3rson** [FireballDWF/securityhub-remediations#37]
Hi @FireballDWF !

I think this step is obsolete since on the AWS Event supplied account we are not allowed to delete the volumes.
Can you please remove that line?

Thanks for the great workshop!

Kind Regards,
Lukas

**Comment by FireballDWF** [comment]
I updated the permissions for the workshop to allow the action in the future
